spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca
spring.datasource.username=biblioteca
spring.datasource.password=biblioteca
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.h2.console.enabled=false
